import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Header/Header";

const geistSans = Inter({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className} bg-white text-gray-800 text-[1rem]  antialiased`}
      >
        <Header />
        {children}
      </body>
      {/* <a href="https://visitorbadge.io/status?path=https%3A%2F%2Ftalep-elm.vercel.app%2F">
        <img src="https://api.visitorbadge.io/api/visitors?path=https%3A%2F%2Ftalep-elm.vercel.app%2F&countColor=%23263759" />
      </a> */}
    </html>
  );
}
